apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: autoscale-scheduler
        plugins:
          multiPoint:
            enabled:
              - name: AutoscaleEnforcer
---
# TODO: put this in the KubeSchedulerConfiguration's plugin config, rather than a separate configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-plugin-config
  namespace: kube-system
data:
  autoscale-enforcer-config.json: |
    {
      "watermark": 0.9,
      "scoring": {
        "minUsageScore": 0.5,
        "maxUsageScore": 0,
        "scorePeak": 0.8,
        "randomize": false
      },
      "schedulerName": "autoscale-scheduler",
      "reconcileWorkers": 16,
      "logSuccessiveFailuresThreshold": 10,
      "startupEventHandlingTimeoutSeconds": 15,
      "patchRetryWaitSeconds": 1,
      "k8sCRUDTimeoutSeconds": 1,
      "nodeMetricLabels": {},
      "ignoredNamespaces": []
    }
