apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: autoscale-scheduler
        plugins:
          multiPoint:
            enabled:
              - name: AutoscaleEnforcer
---
# TODO: put this in the KubeSchedulerConfiguration's plugin config, rather than a separate configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-plugin-config
  namespace: kube-system
data:
  autoscale-enforcer-config.json: |
    {
      "nodeConfig": {
        "cpu": { "watermark": 0.9 },
        "memory": { "watermark": 0.9 },
        "minUsageScore": 0.5,
        "maxUsageScore": 0,
        "scorePeak": 0.8
      },
      "schedulerName": "autoscale-scheduler",
      "eventQueueWorkers": 64,
      "startupEventHandlingTimeoutSeconds": 15,
      "dumpState": {
        "port": 10298,
        "timeoutSeconds": 5
      },
      "migrationDeletionRetrySeconds": 5,
      "doMigration": true,
      "randomizeScores": true
    }
